---
# Required: Beanstalld Settings
beanstalkd:
  host: 127.0.0.1 # matches -l param for beanstalkd
  port: 11300     # matches -p param for beanstalkd
  tubes:
    commands:
      - commands
    events:
      - cli

# Optional: Integration for Envisalink alarm modules
envisalinkd:
  host: 192.168.1.1
  port: 4025
  password: durp12
  code_master: 1234
  code_installer: 5555
  zones:
    '001': Study PIR
    '002': Dungeon PIR
    '003': Bedroom PIR
    '004': Bomb Shelter PIR
    '005': Fire Alarm
    '006': Tamper Switches

# Optional: Email Gateway
alert_email:
  smtp_host: localhost
  smtp_port: 25
  addr_from: alarm@example.com
  addr_to: heythatsmytv@example.com
  # You will want to be selective with triggers, recommend leaving these defaults alone.
  triggers:
    - alarm
    - recovery
    - fault
    - armed
    - disarmed

# Optional: Google Cloud Messaging (Android + iOS apps)
# Refer to the README for more information.
alert_gcm:
  # Sender ID and API key is provided by the Google Project credentials section once Google Cloud Messaging (GCM) has been enabled.
  sender_id: 123
  api_key: xyz


# Optional: Plivo
# Plivo is a text-to-voice phone calling service, see www.plivo.com, it's a
# good option for getting voice calls to your mobile in event of an alarm.
alert_plivo:
  auth_id: SETME
  auth_token: SETME
  call_from: 666
  call_to:
   - 123456789
  triggers:
  - alarm
  - recovery
  - fault

# Optional: Alert URL
# Send alerts to a specific URL endpoint. Multple URLs can be defined, for each
# one the base URL will be used with the event type appended to the end.
alert_url:
  urls:
    - http://example.com/arming/
  triggers:
    - armed
    - disarmed
